In [1]:
import pandas as pd
import numpy as np

In [25]:
df = pd.read_csv('../Summer_2019_Projects/pollution.csv')
df.head()

   No  year  month  day  hour  pm2.5  DEWP  TEMP    PRES cbwd    Iws  Is  Ir
0   1  2010      1    1     0    NaN   -21 -11.0  1021.0   NW   1.79   0   0
1   2  2010      1    1     1    NaN   -21 -12.0  1020.0   NW   4.92   0   0
2   3  2010      1    1     2    NaN   -21 -11.0  1019.0   NW   6.71   0   0
3   4  2010      1    1     3    NaN   -21 -14.0  1019.0   NW   9.84   0   0
4   5  2010      1    1     4    NaN   -20 -12.0  1018.0   NW  12.97   0   0

In [29]:
# Set up the labels for features, target values, and convert the data for use in vector operations
df = pd.get_dummies(df)
df.iloc[:, 5:].head()

,pm2.5,DEWP,TEMP,PRES,Iws,Is,Ir,cbwd_NE,cbwd_NW,cbwd_SE,cbwd_cv
0,NaN,-21,-11.0,1021.0,1.79,0,0,0,1,0,0
1,NaN,-21,-12.0,1020.0,4.92,0,0,0,1,0,0
2,NaN,-21,-11.0,1019.0,6.71,0,0,0,1,0,0
3,NaN,-21,-14.0,1019.0,9.84,0,0,0,1,0,0
4,NaN,-20,-12.0,1018.0,12.97,0,0,0,1,0,0

In [33]:
labels = np.array(df['TEMP'])
df = df.drop('IWS', axis = 1)
features_list = list(df.columns)

KeyError: 'TEMP'